### ISSUE TITLE
hide-lines-invisible-areas should be buffer local

### ISSUE THREAD

**Issue by jpkotta** [vapniks/hide-lines#1]
When I do `hide-lines-show-all`, it makes all hidden lines visible in all buffers.  I think it would be much better to `(make-variable-buffer-local 'hide-lines-invisible-areas)`, and if necessary make a function that loops `hide-lines-show-all` over all buffers (though I don't think it's necessary).

**Comment by bastianbeischer** [comment]
I agree.

**Comment by vapniks** [comment]
Yes, you are right. I have made the change. Thankyou.
